name: Terragrunt Preview

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    name: Plan Terragrunt changes in changed Terramate stacks
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ github.token }}

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      ### Check out the code

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install Terraform and Terragrunt with asdf
        run: |
          asdf plugin add terraform
          asdf plugin add terragrunt
          asdf install terraform
          asdf install terragrunt

      ### Linting

      - name: test bug
        run: terramate create --all-terragrunt
